Fix possible NULL pointer dereference.
tpm2-software/tpm2-pkcs11 pull request #858
Opened 2024-03-16 19:29 UTC by vitek

This caused SEGFAULT when moving sql3 db from 1.7 to 1.9

2024-03-25 14:57 UTC, williamcroberts requested changes

2024-03-25 15:04 UTC, vitek commented on src/lib/db.c
> +        CK_BYTE type = a ? type_from_ptr(a->pValue, a->ulValueLen): 0;
do you mean something like this?

```c
if (a) {
    CK_BYTE type = type_from_ptr(a->pValue, a->ulValueLen);
    if (type != TYPE_BYTE_INT_SEQ) {
        rv = _db_update_tobject_attrs(updb, tobj->id, tobj->attrs);
    }
} else {
   tobject_free(tobj);
   continue;
}
```

or let it fail?

2024-03-25 15:06 UTC, williamcroberts commented on src/lib/db.c
> +        CK_BYTE type = a ? type_from_ptr(a->pValue, a->ulValueLen): 0;
No need for an else clause, as we need it to perform the `tobject_free()` or a memory leak will ensue. We also need to step the database so we can get the next row item to check.

2024-03-25 15:16 UTC, vitek commented on src/lib/db.c
> +        CK_BYTE type = a ? type_from_ptr(a->pValue, a->ulValueLen): 0;
so we shouldn't check `rv` in this case, right?

```
        if (a && rv != CKR_OK) {
            goto error;
        }
```

2024-03-25 17:49 UTC, vitek commented on src/lib/db.c
> +        CK_BYTE type = a ? type_from_ptr(a->pValue, a->ulValueLen): 0;
thanks, fixed

2024-03-25 21:31 UTC, williamcroberts approved these changes

2024-03-25 21:34 UTC, williamcroberts requested changes
So overall the diff is fine, but you need to squash your two commits into one and improve the commit message and add Fixes: #845 and don't forget to signoff on your commit. Thanks!

2024-03-26 06:23 UTC, vitek commented
> So overall the diff is fine, but you need to squash your two commits into one and improve the commit message and add Fixes: #845 and don't forget to signoff on your commit. Thanks!



> So overall the diff is fine, but you need to squash your two commits into one and improve the commit message and add Fixes: #845 and don't forget to signoff on your commit. Thanks!

done

2024-09-04 08:20 UTC, sergiorussia commented
@williamcroberts could u take a look? the fix is critical

2024-09-04 11:23 UTC, sergiorussia commented
also tagging some other active maintainers (https://github.com/orgs/tpm2-software/people) cuz last William's activity was on August 11.

@AndreasFuchsTPM
@pdxjohnny
@JuergenReppSIT
@wxleong

guys could you take a look?
the bug prevents eg from upgrading to Ubuntu 24.04 LTS

ps: after merging this one we could close #849 as a duplicate

2024-09-04 12:09 UTC, merged

2024-09-04 14:53 UTC, williamcroberts commented
I'm gonna start the release process this week.

On Wed, Sep 4, 2024, 07:21 Sergey ***@***.***> wrote:

> @williamcroberts <https://github.com/williamcroberts> could you please
> also give any ETA for next release with the fix?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tpm2-software/tpm2-pkcs11/pull/858#issuecomment-2328833225>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEHNWB5HDVFPOK2YSZBR2SLZU33LJAVCNFSM6AAAAABEZROBW2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRYHAZTGMRSGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>